# Generated by Django 6.0 on 2026-01-02 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_pagetag_taggablepage_taggedpage_taggablepage_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherPageWithTags',
            fields=[
                ('taggablepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.taggablepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.taggablepage',),
        ),
        migrations.CreateModel(
            name='PageWithTags',
            fields=[
                ('taggablepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.taggablepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.taggablepage',),
        ),
    ]
