# Generated by Django 6.0.4 on 2026-04-30 18:37

import core.blocks
import core.models
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_test', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageWithTableOfContents',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('heading', 2), ('heading_list', 3), ('heading_struct', 4), ('heading_stream', 5)], block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'h2'), ('h3', 'h3'), ('h4', 'h4')], 'help_text': 'The level of this heading'}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'The text for this heading', 'max_length': 127, 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('level', 0), ('heading', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (core.blocks.HeadingBlock,), {}), 4: ('wagtail.blocks.StructBlock', [[('heading', 2)]], {}), 5: ('wagtail.blocks.StreamBlock', [[('heading', 2)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.TableOfContentsMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='PageWithTableOfContentsH3',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('heading', 2), ('heading_list', 3), ('heading_struct', 4), ('heading_stream', 5)], block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'h2'), ('h3', 'h3'), ('h4', 'h4')], 'help_text': 'The level of this heading'}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'The text for this heading', 'max_length': 127, 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('level', 0), ('heading', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (core.blocks.HeadingBlock,), {}), 4: ('wagtail.blocks.StructBlock', [[('heading', 2)]], {}), 5: ('wagtail.blocks.StreamBlock', [[('heading', 2)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.TableOfContentsMixin, 'wagtailcore.page'),
        ),
    ]
