# Generated by Django 6.0.5 on 2026-05-29 21:55

import core.models
import django.db.models.deletion
import wagtail.contrib.routable_page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_test', '0002_pagewithtableofcontents_pagewithtableofcontentsh3'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkdownRoutablePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.MarkdownRoutablePageMixin, wagtail.contrib.routable_page.models.RoutablePageMixin, core.models.MarkdownPageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='MarkdownViewablePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.MarkdownPageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='NoTemplateMarkdownPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.MarkdownPageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='NoTemplateMarkdownRoutablePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.MarkdownRoutablePageMixin, wagtail.contrib.routable_page.models.RoutablePageMixin, core.models.MarkdownPageMixin, 'wagtailcore.page'),
        ),
    ]
