# Generated by Django 5.2.7 on 2025-12-28 17:37

import core.models
import django.core.validators
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(default='Book Index Page intro content.', help_text='Intro text for the Book Index Page.')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.FeedMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='BookPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(default='Intro content.', help_text='Intro text for the page, used also in summaries.')),
                ('blurb', wagtail.fields.RichTextField(default='Book blurb', help_text='The blurb for the book.')),
                ('progress', models.PositiveSmallIntegerField(default=0, help_text='The progress through the book, as a percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
