# Generated by Django 6.0 on 2025-12-30 15:06

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_author_bookpage_cover_image_bookauthor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', wagtail.fields.StreamField([('text', 0)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'template': 'patterns/components/streamfield/blocks/text.html'})}, help_text='The notes content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('book', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_notes', to='book.bookpage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
