# Generated by Django 6.0 on 2025-12-30 22:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_booknote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booknote',
            name='content',
            field=wagtail.fields.StreamField([('text', 0), ('code', 3)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'template': 'patterns/components/streamfield/blocks/text.html'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bash', 'Bash/Shell'), ('css', 'CSS'), ('diff', 'diff'), ('html', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('scss', 'SCSS'), ('yaml', 'YAML')], 'help_text': 'Coding language', 'identifier': 'language', 'label': 'Language'}), 2: ('wagtail.blocks.TextBlock', (), {'identifier': 'code', 'label': 'Code'}), 3: ('wagtail.blocks.StructBlock', [[('language', 1), ('code', 2)]], {'template': 'patterns/components/streamfield/blocks/code.html'})}, help_text='The notes content'),
        ),
    ]
