# Generated by Django 6.0.5 on 2026-06-02 05:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_booknote_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booknote',
            name='content',
            field=wagtail.fields.StreamField([('text', 0), ('code', 3), ('heading', 6)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'preview_value': '<b>Rich text</b> content', 'template': 'patterns/components/streamfield/blocks/text.html'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bash', 'Bash/Shell'), ('css', 'CSS'), ('diff', 'diff'), ('go', 'Go'), ('html', 'HTML'), ('javascript', 'JavaScript'), ('json', 'JSON'), ('lua', 'Lua'), ('python', 'Python'), ('scss', 'SCSS'), ('typescript', 'TypeScript'), ('yaml', 'YAML')], 'help_text': 'Coding language', 'label': 'Language'}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Code'}), 3: ('wagtail.blocks.StructBlock', [[('language', 1), ('code', 2)]], {'preview_value': {'code': 'if __name__ == "__main__":\n    print("Hello World!")', 'language': 'python'}, 'template': 'patterns/components/streamfield/blocks/code.html'}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'h2'), ('h3', 'h3'), ('h4', 'h4')], 'help_text': 'The level of this heading'}), 5: ('wagtail.blocks.TextBlock', (), {'help_text': 'The text for this heading', 'max_length': 127, 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('level', 4), ('heading', 5)]], {})}, help_text='The notes content'),
        ),
    ]
