# Generated by Django 5.2.7 on 2025-11-25 07:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='sidebar',
            field=wagtail.fields.StreamField([], blank=True, block_lookup={}, help_text='Sidebar content for the homepage.'),
        ),
    ]
