# Generated by Django 5.2.7 on 2025-12-08 20:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_sidebar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='sidebar',
            field=wagtail.fields.StreamField([('text', 2), ('social', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'The title of this block.', 'max_length': 60, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'The text of this block.', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {}), 3: ('wagtail.blocks.StructBlock', [[('title', 0)]], {})}, help_text='Sidebar content for the homepage.'),
        ),
    ]
