# Generated by Django 6.0 on 2026-01-03 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('article', '0002_alter_articlepage_body'),
        ('core', '0006_pagetag_taggablepage_taggedpage_taggablepage_tags'),
    ]

    operations = [
        # Create TaggablePage entries for existing ArticlePage instances
        migrations.RunSQL(
            sql="""
                INSERT INTO core_taggablepage (page_ptr_id)
                SELECT page_ptr_id
                FROM article_articlepage
                WHERE page_ptr_id NOT IN (SELECT page_ptr_id FROM core_taggablepage)
            """,
            reverse_sql="""
                DELETE FROM core_taggablepage
                WHERE page_ptr_id IN (SELECT page_ptr_id FROM article_articlepage)
            """,
        ),
        
        # Change the inheritance without touching the database schema
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # Remove old page_ptr relationship  
                migrations.RemoveField(
                    model_name='articlepage',
                    name='page_ptr',
                ),
                # Add new taggablepage_ptr relationship
                migrations.AddField(
                    model_name='articlepage',
                    name='taggablepage_ptr',
                    field=models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='core.taggablepage',
                    ),
                ),
            ],
            # Rename the column in the database
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE article_articlepage RENAME COLUMN page_ptr_id TO taggablepage_ptr_id',
                    reverse_sql='ALTER TABLE article_articlepage RENAME COLUMN taggablepage_ptr_id TO page_ptr_id',
                ),
            ],
        ),
    ]
