# Generated by Django 6.0 on 2026-01-03 08:02

import django.db.models.deletion
from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ('article', '0002_alter_articlepage_body'),
        ('core', '0006_pagetag_taggablepage_taggedpage_taggablepage_tags'),
    ]

    operations = [
        # Create TaggablePage entries for existing ArticlePage instances
        migrations.RunSQL(
            sql="""
                INSERT INTO core_taggablepage (page_ptr_id)
                SELECT page_ptr_id
                FROM article_articlepage
                WHERE page_ptr_id NOT IN (SELECT page_ptr_id FROM core_taggablepage)
            """,
            reverse_sql="""
                DELETE FROM core_taggablepage
                WHERE page_ptr_id IN (SELECT page_ptr_id FROM article_articlepage)
            """,
        ),
        
        # Need to change the base.
        # Recreate the ArticlePage model in state so it inherits from TaggablePage
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name='ArticlePage'),
                migrations.CreateModel(
                    name='ArticlePage',
                    fields=[
                        ('taggablepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.taggablepage')),
                        ('intro', wagtail.fields.RichTextField(default='Article intro content.', help_text='Intro text for the article page.')),
                        ('body', wagtail.fields.StreamField([('text', 0), ('code', 3)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'template': 'patterns/components/streamfield/blocks/text.html'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bash', 'Bash/Shell'), ('css', 'CSS'), ('diff', 'diff'), ('html', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('scss', 'SCSS'), ('yaml', 'YAML')], 'help_text': 'Coding language', 'identifier': 'language', 'label': 'Language'}), 2: ('wagtail.blocks.TextBlock', (), {'identifier': 'code', 'label': 'Code'}), 3: ('wagtail.blocks.StructBlock', [[('language', 1), ('code', 2)]], {'template': 'patterns/components/streamfield/blocks/code.html'})}, help_text='Main body content for the article page.')),
                    ],
                    options={
                        'abstract': False,
                    },
                    bases=('core.taggablepage',),
                ),
            ],
            # Actually - just rename the column in the database
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE article_articlepage RENAME COLUMN page_ptr_id TO taggablepage_ptr_id',
                    reverse_sql='ALTER TABLE article_articlepage RENAME COLUMN taggablepage_ptr_id TO page_ptr_id',
                ),
            ],
        ),
    ]
