# Generated by Django 6.0.4 on 2026-04-08 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_articlepage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='TILIndexPage',
            fields=[
                ('articleindexpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.articleindexpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('article.articleindexpage',),
        ),
        migrations.CreateModel(
            name='TILPage',
            fields=[
                ('articlepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.articlepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('article.articlepage',),
        ),
    ]
