# Generated by Django 5.2.7 on 2025-11-23 10:00

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=wagtail.fields.RichTextField(default='Blog intro content.', help_text='Intro text for the homepage.'),
        ),
    ]
