# Generated by Django 5.2.7 on 2025-12-08 20:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_socialmedialinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialinks',
            name='links',
            field=wagtail.fields.StreamField([('link', 3)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'The display text of this social media link', 'max_length': 60, 'required': True}), 1: ('wagtail.blocks.URLBlock', (), {'help_text': 'The URL of this social media link', 'required': True}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('github', 'GitHub'), ('bluesky', 'BlueSky'), ('feed', 'Feed')], 'help_text': 'The type of social media link'}), 3: ('wagtail.blocks.StructBlock', [[('display', 0), ('url', 1), ('type', 2)]], {})}, help_text='Social Media Links'),
        ),
    ]
