# Generated by Django 6.0.1 on 2026-02-18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_socialmedialinks_links"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name="AnalyticsSettings",
                ),
            ],
        ),
    ]
