# Generated by Django 6.0.1 on 2026-02-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0009_remove_analyticssettings_state"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE core_analyticssettings RENAME TO analytics_analyticssettings;",
                    reverse_sql="ALTER TABLE analytics_analyticssettings RENAME TO core_analyticssettings;",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="AnalyticsSettings",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "umami_id",
                            models.CharField(
                                blank=True,
                                max_length=50,
                                verbose_name="The Umami Website ID",
                            ),
                        ),
                        (
                            "site",
                            models.OneToOneField(
                                editable=False,
                                on_delete=django.db.models.deletion.CASCADE,
                                to="wagtailcore.site",
                            ),
                        ),
                    ],
                    options={
                        "abstract": False,
                    },
                ),
            ],
        ),
    ]
