# Generated by Django 6.0.5 on 2026-05-25 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_analyticssettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalyticsSettings',
        ),
    ]
